'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { Map as LMap, LayerGroup, LatLngBounds } from 'leaflet';
import { ArrowDownUp, ArrowRight, Check, ChevronRight, Clock3, Compass, Flower2, Footprints, HelpCircle, Layers, Leaf, List, LocateFixed, MapPin, Minus, Phone, Plus, RotateCcw, Search, SlidersHorizontal, Sparkles, Waves, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty';

type Shop = { id:number; name:string; district:string; area:string; category:string; price:number; lat:number; lng:number; image:string; hours:string; tag:string };
const shops: Shop[] = [
{id:1,name:'온유 테라피',district:'고양',area:'일산동구 정발산동',category:'아로마',price:65000,lat:37.6667,lng:126.7779,image:'treatment',hours:'10:00 – 22:00',tag:'차분한 1인 케어'},
{id:2,name:'라온 타이',district:'고양',area:'일산서구 주엽동',category:'타이',price:45000,lat:37.6727,lng:126.7608,image:'reception',hours:'11:00 – 23:00',tag:'가볍게 풀어내는 하루'},
{id:3,name:'포레스트 스파',district:'고양',area:'일산동구 백석동',category:'아로마',price:80000,lat:37.6474,lng:126.7885,image:'oils',hours:'10:00 – 21:00',tag:'아로마 오일 케어'},
{id:4,name:'리프 바디케어',district:'고양',area:'일산서구 대화동',category:'스포츠',price:55000,lat:37.6793,lng:126.7458,image:'treatment',hours:'10:00 – 22:00',tag:'활기찬 일상을 위해'},
{id:5,name:'하루 쉼',district:'파주',area:'운정동',category:'아로마',price:60000,lat:37.7143,lng:126.7515,image:'reception',hours:'11:00 – 22:00',tag:'나만의 조용한 시간'},
{id:6,name:'웰니스 풋',district:'파주',area:'야당동',category:'발 마사지',price:35000,lat:37.7102,lng:126.7636,image:'oils',hours:'10:00 – 21:00',tag:'가벼운 발걸음'},
{id:7,name:'소담 테라피',district:'고양',area:'덕양구 화정동',category:'스포츠',price:50000,lat:37.6337,lng:126.8326,image:'treatment',hours:'10:00 – 22:00',tag:'세심한 바디케어'},
{id:8,name:'반디 아로마',district:'파주',area:'금촌동',category:'아로마',price:70000,lat:37.7596,lng:126.7734,image:'reception',hours:'11:00 – 22:00',tag:'향기로 채우는 휴식'},
{id:9,name:'무드 타이',district:'고양',area:'일산동구 마두동',category:'타이',price:50000,lat:37.6574,lng:126.7881,image:'oils',hours:'11:00 – 23:00',tag:'편안한 스트레칭'},
{id:10,name:'더 편안',district:'파주',area:'동패동',category:'스포츠',price:55000,lat:37.7246,lng:126.7286,image:'treatment',hours:'10:00 – 22:00',tag:'일상 속 재충전'},
{id:11,name:'오롯이 풋스파',district:'고양',area:'일산서구 탄현동',category:'발 마사지',price:40000,lat:37.6947,lng:126.7623,image:'reception',hours:'10:00 – 21:00',tag:'따뜻한 족욕과 휴식'},
{id:12,name:'느린 오후',district:'파주',area:'목동동',category:'타이',price:45000,lat:37.7379,lng:126.7516,image:'oils',hours:'11:00 – 22:00',tag:'여유로운 타이 케어'},
];
const categories = [{name:'전체',icon:Sparkles},{name:'아로마',icon:Leaf},{name:'타이',icon:Waves},{name:'스포츠',icon:Compass},{name:'발 마사지',icon:Footprints}];
const money = (v:number) => v.toLocaleString('ko-KR');
export default function Home(){
 const [query,setQuery]=useState(''); const [region,setRegion]=useState('전체 지역'); const [category,setCategory]=useState('전체'); const [price,setPrice]=useState('전체 가격'); const [sort,setSort]=useState('추천순'); const [selected,setSelected]=useState<number|null>(1);
 const [details,setDetails]=useState(false); const [help,setHelp]=useState(false); const [phone,setPhone]=useState(false); const [mobileList,setMobileList]=useState(false); const [mapReady,setMapReady]=useState(false); const [mapRevision,setMapRevision]=useState(0); const [mapError,setMapError]=useState(false); const [bounds,setBounds]=useState<LatLngBounds|null>(null); const [moved,setMoved]=useState(false); const [notice,setNotice]=useState('');
 const mapNode=useRef<HTMLDivElement>(null); const map=useRef<LMap|null>(null); const markers=useRef<LayerGroup|null>(null); const leaflet=useRef<typeof import('leaflet')|null>(null); const locationLayer=useRef<import('leaflet').CircleMarker|null>(null);
 const filtered=useMemo(()=>shops.filter(s=>(region==='전체 지역'||s.district===region)&&(category==='전체'||s.category===category)&&(price==='전체 가격'||(price==='5만원 이하'?s.price<=50000:price==='5–7만원'?s.price>50000&&s.price<=70000:s.price>70000))&&`${s.name} ${s.district} ${s.area} ${s.category}`.includes(query.trim())&&(!bounds||bounds.contains([s.lat,s.lng]))).sort((a,b)=>sort==='낮은 가격순'?a.price-b.price:a.id-b.id),[query,region,category,price,sort,bounds]);
 const active=filtered.find(s=>s.id===selected);
 const choose=useCallback((s:Shop)=>{setSelected(s.id);map.current?.flyTo([s.lat,s.lng],Math.max(map.current.getZoom(),14),{duration:.6});document.getElementById(`shop-${s.id}`)?.scrollIntoView({behavior:'smooth',block:'nearest'});},[]);
 useEffect(()=>{let cancelled=false;let observer:ResizeObserver|null=null;import('leaflet').then(L=>{if(cancelled||!mapNode.current)return;leaflet.current=L;const instance=L.map(mapNode.current,{zoomControl:false,minZoom:10,maxZoom:18,maxBounds:[[37.48,126.5],[37.96,127.08]],maxBoundsViscosity:.8}).setView([37.697,126.773],12);map.current=instance;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>'}).addTo(instance);let failures=0;tiles.on('tileerror',()=>{if(++failures>=3)setMapError(true);});tiles.on('tileload',()=>{failures=0;setMapError(false);});markers.current=L.layerGroup().addTo(instance);instance.on('moveend',()=>setMoved(true));instance.on('zoomend',()=>setMapRevision(v=>v+1));observer=new ResizeObserver(()=>instance.invalidateSize());observer.observe(mapNode.current);setMapReady(true);}).catch(()=>setMapError(true));return()=>{cancelled=true;observer?.disconnect();map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{
  if(!mapReady||!leaflet.current||!markers.current||!map.current)return;
  const L=leaflet.current;const instance=map.current;markers.current.clearLayers();
  const groups:Shop[][]=[];
  for(const s of filtered){const point=instance.latLngToLayerPoint([s.lat,s.lng]);const group=groups.find(g=>{const other=instance.latLngToLayerPoint([g[0].lat,g[0].lng]);return Math.abs(point.x-other.x)<94&&Math.abs(point.y-other.y)<46;});if(group)group.push(s);else groups.push([s]);}
  for(const group of groups){
   if(group.length>1){const center=L.latLngBounds(group.map(s=>[s.lat,s.lng] as [number,number])).getCenter();const icon=L.divIcon({className:'cluster-marker',html:`<span>${group[0].district}<strong>${group.length}</strong></span>`,iconSize:[84,40],iconAnchor:[42,20]});const marker=L.marker(center,{icon,keyboard:true,title:`${group[0].district} 매장 ${group.length}곳 확대`}).addTo(markers.current);marker.on('click',()=>instance.flyTo(center,Math.min(instance.getZoom()+2,18),{duration:.5}));marker.getElement()?.setAttribute('aria-label',`${group[0].district} 매장 ${group.length}곳 확대`);continue;}
   const s=group[0];const isActive=s.id===selected;const icon=L.divIcon({className:`price-marker ${isActive?'is-selected':''}`,html:`<span>${money(s.price)}<small>원</small></span>`,iconSize:[88,39],iconAnchor:[44,46]});
   const marker=L.marker([s.lat,s.lng],{icon,title:`${s.name}, ${money(s.price)}원`,keyboard:true,zIndexOffset:isActive?1000:0}).addTo(markers.current);marker.on('click',()=>{setSelected(s.id);document.getElementById(`shop-${s.id}`)?.scrollIntoView({behavior:'smooth',block:'nearest'});});const el=marker.getElement();el?.setAttribute('role','button');el?.setAttribute('aria-label',`${s.name}, ${s.category}, ${money(s.price)}원`);el?.setAttribute('aria-pressed',String(isActive));
  }
 },[filtered,selected,mapReady,mapRevision]);

 useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);}},[notice]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tools:Tool[]=[{name:'search_shops',description:'Filter the visible sample shop map and list by text, region, and massage category.',inputSchema:{type:'object',properties:{query:{type:'string'},region:{type:'string',enum:['전체 지역','고양','파주']},category:{type:'string',enum:['전체','아로마','타이','스포츠','발 마사지']}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{
   if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected search parameters.');
   const p=input as Record<string,unknown>;
   if(Object.keys(p).some(k=>!['query','region','category'].includes(k))||(p.query!==undefined&&typeof p.query!=='string')||(p.region!==undefined&&!['전체 지역','고양','파주'].includes(String(p.region)))||(p.category!==undefined&&!categories.some(c=>c.name===p.category)))throw new Error('Invalid search parameters.');
   const q=String(p.query??'');const r=String(p.region??'전체 지역');const c=String(p.category??'전체');
   setQuery(q);setRegion(r);setCategory(c);setPrice('전체 가격');setBounds(null);setSelected(q===''&&r==='전체 지역'&&c==='전체'?1:null);
   map.current?.setView(r==='파주'?[37.731,126.751]:r==='고양'?[37.665,126.785]:[37.697,126.773],r==='전체 지역'?12:13);
   await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));
   return {shops:shops.filter(s=>(r==='전체 지역'||s.district===r)&&(c==='전체'||s.category===c)&&`${s.name} ${s.district} ${s.area} ${s.category}`.includes(q.trim())).map(s=>({id:s.id,name:s.name,price:s.price})),sample:true};
  }}];
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  return()=>lifecycle.abort();
 },[]);
 const reset=()=>{setQuery('');setRegion('전체 지역');setCategory('전체');setPrice('전체 가격');setBounds(null);setSelected(1);map.current?.setView([37.697,126.773],12);};
 const changeRegion=(v:string)=>{setRegion(v);setBounds(null);map.current?.flyTo(v==='파주'?[37.731,126.751]:v==='고양'?[37.665,126.785]:[37.697,126.773],v==='전체 지역'?12:13);};
 const locate=()=>{if(!navigator.geolocation){setNotice('이 브라우저에서는 내 위치를 사용할 수 없어요. 지역을 직접 선택해 주세요.');return;}setNotice('현재 위치를 확인하고 있어요.');navigator.geolocation.getCurrentPosition(p=>{const{latitude,longitude}=p.coords;if(latitude<37.55||latitude>37.92||longitude<126.55||longitude>127){setNotice('현재 고양·파주 지역만 안내하고 있어요. 지역을 선택해 둘러보세요.');return;}locationLayer.current?.remove();if(leaflet.current&&map.current)locationLayer.current=leaflet.current.circleMarker([latitude,longitude],{radius:8,fillColor:'#228ce6',color:'#fff',weight:3,fillOpacity:1}).addTo(map.current);map.current?.flyTo([latitude,longitude],14);setNotice('내 위치로 이동했어요.');},()=>setNotice('위치 정보를 확인할 수 없어요. 지역을 직접 선택해 주세요.'),{timeout:10000,maximumAge:60000});};
 return <main className="app-shell">
 <header className="site-header"><a className="brand" href="/" aria-label="쉼 홈"><span className="brand-icon"><Flower2 size={28} strokeWidth={1.5}/></span><span className="brand-word">쉼<span>SUIM</span></span></a><span className="brand-caption">일상 가까이, 편안한 쉼</span><div className="header-nav"><span className="nav-current"><MapPin size={17}/>지도에서 찾기</span></div><div className="header-actions"><span className="sample-label">PREVIEW <span>샘플 서비스</span></span><button className="help-button" onClick={()=>setHelp(true)}><HelpCircle size={18}/><span>이용 안내</span></button></div></header>
 <div className="filter-bar"><div className="search-box"><Search size={20}/><input aria-label="지역 또는 매장명 검색" placeholder="어디에서 쉬고 싶으세요?" value={query} onChange={e=>{setQuery(e.target.value);setBounds(null);}}/>{query&&<button aria-label="검색어 지우기" onClick={()=>setQuery('')}><X size={16}/></button>}</div><div className="category-filters" aria-label="마사지 종류">{categories.map(({name,icon:Icon})=><button key={name} aria-pressed={category===name} className={`category-chip ${category===name?'active':''}`} onClick={()=>{setCategory(name);setBounds(null);}}><Icon size={17}/>{name}</button>)}</div><div className="price-filter"><Select value={price} onValueChange={v=>{if(v)setPrice(v);}}><SelectTrigger aria-label="가격 필터" className="filter-select"><SlidersHorizontal size={16}/><SelectValue/></SelectTrigger><SelectContent>{['전체 가격','5만원 이하','5–7만원','7만원 초과'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div></div>
 <div className="workspace"><aside className={`results-panel ${mobileList?'mobile-open':''}`} aria-label="매장 검색 결과"><div className="results-heading"><div className="eyebrow">A LITTLE BREAK, NEAR YOU</div><h1>오늘, 나를 위한<br/><span>쉼을 찾아보세요.</span></h1><p>고양·파주의 편안한 공간을 모았어요.</p></div><div className="result-toolbar"><p>주변 매장 <strong>{filtered.length}</strong><span>곳</span></p><Select value={sort} onValueChange={v=>v&&setSort(v)}><SelectTrigger aria-label="매장 정렬" className="sort-select"><ArrowDownUp size={14}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="추천순">추천순</SelectItem><SelectItem value="낮은 가격순">낮은 가격순</SelectItem></SelectContent></Select><button className="mobile-close icon-button" aria-label="목록 닫기" onClick={()=>setMobileList(false)}><X size={19}/></button></div>
 <div className="shop-list">{filtered.map(s=><button id={`shop-${s.id}`} key={s.id} className={`shop-card ${selected===s.id?'selected':''}`} onClick={()=>{choose(s);setMobileList(false);}} aria-pressed={selected===s.id}><div className="shop-card-top"><div className={`shop-image image-${s.image}`}><img src={`/images/${s.image}.jpg`} alt={`${s.name}의 분위기를 보여주는 참고 이미지`}/><span>{s.category}</span></div><div className="shop-info"><span className="shop-area">{s.district} · {s.area}</span><h2>{s.name}</h2><p className="shop-tag">{s.tag}</p><p className="shop-hours"><Clock3 size={12}/>{s.hours}</p></div></div><div className="shop-card-bottom"><span>대표 코스 <span>60분</span></span><strong>{money(s.price)}<small>원~</small><ChevronRight size={16}/></strong></div></button>)}{!filtered.length&&<Empty className="empty-result"><EmptyHeader><Search size={30}/><EmptyTitle>조건에 맞는 매장이 없어요</EmptyTitle><EmptyDescription>다른 지역이나 검색 조건으로 찾아보세요.</EmptyDescription></EmptyHeader><button className="solid-button" onClick={reset}>필터 초기화</button></Empty>}<div className="list-footnote"><Flower2 size={17}/><p>잠깐의 쉼이, 더 좋은 하루로.</p><small>매장 정보와 사진은 시연용 샘플입니다.</small></div></div></aside>
 <section className="map-panel" aria-label="고양·파주 마사지샵 지도"><div ref={mapNode} className="actual-map" aria-label="드래그와 확대·축소가 가능한 매장 지도"/>{!mapReady&&!mapError&&<div className="map-loading"><Flower2 size={32}/><span>주변의 쉼을 불러오고 있어요</span></div>}<div className="map-topbar"><div className="region-picker"><MapPin size={17}/><Select value={region} onValueChange={v=>v&&changeRegion(v)}><SelectTrigger aria-label="지역 선택" className="region-select"><SelectValue/></SelectTrigger><SelectContent>{['전체 지역','고양','파주'].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select><span className="region-divider"/><span className="service-area">고양 · 파주</span></div><div className="map-tag"><span/>나에게 가까운 쉼</div></div>{moved&&<button className="search-area" onClick={()=>{if(map.current)setBounds(map.current.getBounds());setMoved(false);}}><RotateCcw size={15}/>이 지역에서 다시 검색</button>}{bounds&&<button className="bounds-reset" onClick={()=>{setBounds(null);setMoved(false);}}>지도 범위 검색 중<X size={13}/></button>}{mapError&&<div className="map-error" role="status">지도를 불러오지 못했어요. 네트워크를 확인해 주세요.<button onClick={()=>window.location.reload()}>다시 시도</button></div>}
 <div className="map-controls"><button onClick={locate} aria-label="내 위치로 이동" title="내 위치로 이동"><LocateFixed size={21}/></button><div className="zoom-group"><button onClick={()=>map.current?.zoomIn()} aria-label="지도 확대"><Plus size={22}/></button><button onClick={()=>map.current?.zoomOut()} aria-label="지도 축소"><Minus size={22}/></button></div><button onClick={()=>{setBounds(null);map.current?.fitBounds(shops.map(s=>[s.lat,s.lng] as [number,number]),{padding:[65,65]});}} aria-label="전체 매장 보기" title="전체 매장 보기"><Layers size={20}/></button></div><button className="mobile-list-button" onClick={()=>setMobileList(true)}><List size={17}/>목록 보기<span>{filtered.length}</span></button>
 {active&&<div className="map-selected-card"><button className="selected-close" aria-label="선택한 매장 닫기" onClick={()=>setSelected(null)}><X size={16}/></button><button className="selected-main" onClick={()=>setDetails(true)}><img className={`image-${active.image}`} src={`/images/${active.image}.jpg`} alt="선택한 매장의 참고 이미지"/><div><span className="selected-category">{active.category}<span> · {active.district}</span></span><h2>{active.name}</h2><p>60분<strong>{money(active.price)}<small>원~</small></strong></p></div></button><div className="selected-actions"><button onClick={()=>setDetails(true)}>매장 정보<ArrowRight size={16}/></button><button className="call-button" onClick={()=>setPhone(true)}><Phone size={16}/>전화 문의</button></div></div>}<div className="map-bottom-label"><span className="teal-dot"/>표시된 가격은 60분 대표 코스 기준이에요.</div>{notice&&<div className="notice" role="status">{notice}</div>}</section></div>
 <Sheet open={details&&!!active} onOpenChange={setDetails}><SheetContent className="detail-sheet">{active&&<><img className="detail-image" src={`/images/${active.image}.jpg`} alt="샘플 매장 참고 이미지"/><SheetHeader><span className="selected-category">{active.category} · {active.district}</span><SheetTitle className="detail-title">{active.name}</SheetTitle><SheetDescription>{active.tag}. 바쁜 하루 사이, 편안한 공간에서 나에게 집중하는 시간을 가져보세요.</SheetDescription></SheetHeader><div className="detail-body"><p><MapPin size={18}/>{active.district}시 {active.area}</p><p><Clock3 size={18}/>{active.hours}</p><h3>프로그램 안내</h3><div className="program-row"><span>{active.category} 기본 코스<small>60분</small></span><strong>{money(active.price)}원</strong></div><div className="program-row"><span>{active.category} 집중 코스<small>90분</small></span><strong>{money(active.price+25000)}원</strong></div><p className="sample-note">시연용 가상 매장입니다. 위치·가격·영업시간과 사진은 실제 매장 정보가 아닙니다.</p></div><div className="detail-footer"><button className="solid-button" onClick={()=>setPhone(true)}><Phone size={18}/>전화로 문의하기</button></div></>}</SheetContent></Sheet>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="info-dialog"><DialogHeader><span className="dialog-icon"><Flower2 size={26}/></span><DialogTitle>나에게 맞는 쉼, 간편하게</DialogTitle><DialogDescription>로그인 없이 고양·파주의 매장을 둘러보세요.</DialogDescription></DialogHeader><ol className="guide-list"><li><span>1</span><div><strong>지도에서 찾아보세요</strong><p>지역과 마사지 종류를 선택하고 지도를 움직여보세요.</p></div></li><li><span>2</span><div><strong>가격과 정보를 한눈에</strong><p>지도 위 가격을 누르면 해당 매장의 정보가 열려요.</p></div></li><li><span>3</span><div><strong>마음에 들면 전화로 문의</strong><p>예약과 결제는 제공하지 않아요. 매장에 직접 문의하세요.</p></div></li></ol><p className="sample-note">현재 페이지는 가상 매장으로 구성한 제안용 샘플이며, 실제 전화 연결은 하지 않습니다.</p><button className="solid-button" onClick={()=>setHelp(false)}>둘러보기<ArrowRight size={16}/></button></DialogContent></Dialog>
 <Dialog open={phone} onOpenChange={setPhone}><DialogContent className="info-dialog"><DialogHeader><span className="dialog-icon"><Phone size={24}/></span><DialogTitle>전화 문의 미리보기</DialogTitle><DialogDescription>실제 서비스에서는 이 버튼으로 매장에 바로 전화할 수 있어요. 지금은 가상 매장을 사용하는 샘플이므로 전화가 연결되지 않습니다.</DialogDescription></DialogHeader><button className="solid-button" onClick={()=>setPhone(false)}><Check size={17}/>확인했어요</button></DialogContent></Dialog>
 </main>;
}
